// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVCo04TODYTK_4vAPrLb9cvH0l6BBVDMw',
    appId: '1:327442522135:web:5f7d2a8a5b3c8084287c52',
    messagingSenderId: '327442522135',
    projectId: 'major-project-57307',
    authDomain: 'major-project-57307.firebaseapp.com',
    storageBucket: 'major-project-57307.firebasestorage.app',
    measurementId: 'G-700ZQMDR9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Lxm8Kovnn-KdL0DOtKUPDKaXSHFeQls',
    appId: '1:327442522135:android:a3417fc6234134bd287c52',
    messagingSenderId: '327442522135',
    projectId: 'major-project-57307',
    storageBucket: 'major-project-57307.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgkJu2_fyvRr-EK-qf0T-YP8sRjyxbgRM',
    appId: '1:327442522135:ios:ea45ad746cfd9783287c52',
    messagingSenderId: '327442522135',
    projectId: 'major-project-57307',
    storageBucket: 'major-project-57307.firebasestorage.app',
    iosBundleId: 'com.example.academiax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgkJu2_fyvRr-EK-qf0T-YP8sRjyxbgRM',
    appId: '1:327442522135:ios:ea45ad746cfd9783287c52',
    messagingSenderId: '327442522135',
    projectId: 'major-project-57307',
    storageBucket: 'major-project-57307.firebasestorage.app',
    iosBundleId: 'com.example.academiax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVCo04TODYTK_4vAPrLb9cvH0l6BBVDMw',
    appId: '1:327442522135:web:af374ccfefdc1519287c52',
    messagingSenderId: '327442522135',
    projectId: 'major-project-57307',
    authDomain: 'major-project-57307.firebaseapp.com',
    storageBucket: 'major-project-57307.firebasestorage.app',
    measurementId: 'G-8Z10YKNPTN',
  );
  
}
